version: '3.2'

services:
  web:
    image: dimadockerid/member-service:part2
    build: .
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=test
      - DATABASE_PORT=27017
  db:
    image: mongo
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    links:
     - db:mongo